export type PantryUnit = 'pcs' | 'g' | 'kg' | 'ml' | 'l' | 'tbsp' | 'tsp' | 'cup';

export interface PantryItem {
  id: string;
  name: string;
  qty?: number;
  unit?: PantryUnit;
  source: 'photo' | 'manual';
  confidence?: number;
  lastSeenAt: string;
  lastUsed?: string;
  used?: boolean;
  favorite?: boolean;
}

export interface DetectedItem {
  id: string;
  name: string;
  confidence: number;
}

export interface Preferences {
  diet: 'Regular' | 'Vegetarian' | 'Vegan' | 'Pescatarian' | 'Keto' | 'Gluten-free';
  goals: string[];
  mealPreferences: string[];
  allergies: string[];
  dislikes: string[];
  notificationTime: string;
  notificationDays: string[];
  servings: number;
  privacyNoStoreImages?: boolean;
}

export interface Ingredient {
  name: string;
  qty?: number;
  unit?: string;
  optional?: boolean;
  pantryName?: string;
}

export interface Step {
  order: number;
  text: string;
  minutes?: number;
}

export interface Recipe {
  id: string;
  title: string;
  description?: string;
  timeMin: number;
  kcal?: number;
  tags: string[];
  allergens?: string[];
  needs: string[];
  optional?: string[];
  ingredients: Ingredient[];
  steps: Step[];
  substitutions?: Record<string, string>;
  healthNote?: string;
  difficulty?: 'easy' | 'medium' | 'hard';
  cuisine?: string;
  platingTips?: string;
  winePairing?: string;
  aiGenerated?: boolean;
}

export interface SuggestionPick {
  date: string;
  recipeIds: string[];
  indexShown: number;
}

export interface Signal {
  ts: string;
  type: 'viewed' | 'accepted' | 'another' | 'skip';
  recipeId?: string;
  tags?: string[];
  needs?: string[];
}

export interface LearningState {
  tagWeights: Record<string, number>;
  tagDecayAnchor?: string;
  lastUpdated?: string;
}

export interface UsageEvent {
  ts: string;
  recipeId: string;
  recipeName: string;
  ingredients: { name: string; qty?: number; unit?: string }[];
}

export interface ShoppingItem {
  id: string;
  name: string;
  reason: 'low_stock' | 'used_up' | 'missing_from_recipe';
  suggestedQty?: number;
  unit?: PantryUnit;
  autoGenerated: boolean;
  addedAt: string;
  bought?: boolean;
}

export interface ShoppingState {
  queue: ShoppingItem[];
  lastGenerated?: string;
}
